config/routes.rb
Rails.application.routes.draw do
resources :sessions
  resources :users
  root 'home#index'
  get "sign_up", "users#new", :controller => :users,:action => :new
  get "sign_in", "sessions#new",:controller => :sessions, :action => :new
  get "log_out","sessions#destroy",:controller => :sessions,:action => :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password,:password_confirmation
 before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email],params[:password])
  	if user
  		session[:user_id] = user.id
  	  		redirect_to root_path
  	else
  		render :new
  	end
  end

def destroy
  session[:user_id] = nil
  redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to root_path
  	else 
  		render :new
  	end
  end

  private

  def user_params
  	params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authscrach</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<% if current_user %>
<%= current_user.email %>
<%= link_to "Signout", log_out_path%>
<%else%>
<%= link_to "Signin", sign_in_path %>
<%= link_to "Signup", sign_up_path %>
<%end%>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>new User</h1>
<%= form_for @user do |f|%>

<div>
<%= f.label :Email%>
<%= f.text_field :email %>
</div><br/>


<div>
<%= f.label :password%>
<%= f.password_field :password %>
</div><br/>


<div>
<%= f.label :password_confirmation%>
<%= f.password_field :password_confirmation %>
</div><br/>
<%= f.submit :signup %>
<% end%>